version: '3.4'

services:
  myfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  mybackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

